## COUNTER

In [1]:
from collections import Counter

In [2]:
c = Counter()

In [3]:
c['red'] += 1
print(c)

Counter({'red': 1})


In [4]:
cars = ['red', 'blue', 'black', 'black', 'black', 'red', 'blue', 'red', 'white']

In [5]:
c = Counter()
for car in cars:
    c[car] += 1

print(c)

Counter({'red': 3, 'black': 3, 'blue': 2, 'white': 1})


In [6]:
c_new = Counter(cars)
print(c_new)

Counter({'red': 3, 'black': 3, 'blue': 2, 'white': 1})


In [7]:
c_new['black']

3

In [8]:
print(sum(c.values()))

9


In [9]:
print(c.values())

dict_values([3, 2, 3, 1])


### ОПЕРАЦИИ С COUNTER

In [10]:
cars_moscow = ['black', 'black', 'white', 'black', 'black', 'white', 'yellow', 'yellow', 'yellow']
cars_spb = ['red', 'black', 'black', 'white', 'white', 'yellow', 'yellow', 'red', 'white']

In [11]:
counter_moscow = Counter(cars_moscow)
counter_spb = Counter(cars_spb)
 
print(counter_moscow)
print(counter_spb)

Counter({'black': 4, 'yellow': 3, 'white': 2})
Counter({'white': 3, 'red': 2, 'black': 2, 'yellow': 2})


In [12]:
print(counter_moscow + counter_spb)

Counter({'black': 6, 'white': 5, 'yellow': 5, 'red': 2})


In [13]:
print(counter_moscow)
print(counter_spb)

counter_moscow.subtract(counter_spb)
print(counter_moscow)

Counter({'black': 4, 'yellow': 3, 'white': 2})
Counter({'white': 3, 'red': 2, 'black': 2, 'yellow': 2})
Counter({'black': 2, 'yellow': 1, 'white': -1, 'red': -2})


In [14]:
counter_moscow = Counter(cars_moscow)
counter_spb = Counter(cars_spb)

print(counter_moscow - counter_spb)

Counter({'black': 2, 'yellow': 1})


### ДОПОЛНИТЕЛЬНЫЕ ФУНКЦИИ

In [15]:
print(*counter_moscow.elements())

black black black black white white yellow yellow yellow


In [16]:
print(list(counter_moscow))

['black', 'white', 'yellow']


In [17]:
print(dict(counter_moscow))

{'black': 4, 'white': 2, 'yellow': 3}


In [18]:
print(counter_moscow.most_common())

[('black', 4), ('yellow', 3), ('white', 2)]


In [19]:
print(counter_moscow.most_common(2))

[('black', 4), ('yellow', 3)]


In [20]:
print(len(counter_spb))

4


## DEFAULTDICT

In [21]:
students = [('Ivanov',1),('Smirnov',4),('Petrov',3),('Kuznetsova',1),
            ('Nikitina',2),('Markov',3),('Pavlov',2)]

In [22]:
groups = dict()

for student, group in students:
    if group not in groups:
        groups[group] = list()
    groups[group].append(student)

print(groups)

{1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov']}


In [23]:
groups = dict()
 
for student, group in students:
    groups[group].append(student)
 
print(groups)

KeyError: 1

In [ ]:
from collections import defaultdict

In [ ]:
groups = defaultdict(list)

In [ ]:
for student, group in students:
    groups[group].append(student)
 
print(groups)

defaultdict(<class 'list'>, {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov']})


In [ ]:
print(groups[3])

['Petrov', 'Markov']


In [ ]:
print(groups[2021])

[]


In [ ]:
print(groups)

defaultdict(<class 'list'>, {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov'], 2021: []})


In [ ]:
dict_object = dict()
defaultdict_object = defaultdict()
 
print(type(dict_object))
print(type(defaultdict_object))

<class 'dict'>
<class 'collections.defaultdict'>


# 3. Модуль Collections. Deque и OrderedDict

### ORDEREDDICT

In [ ]:
data = [('Ivan', 19),('Mark', 25),('Andrey', 23),('Maria', 20)]
client_ages = dict(data)
print(client_ages)

{'Ivan': 19, 'Mark': 25, 'Andrey': 23, 'Maria': 20}


In [ ]:
from collections import OrderedDict
data = [('Ivan', 19),('Mark', 25),('Andrey', 23),('Maria', 20)]
ordered_client_ages = OrderedDict(data)
print(ordered_client_ages)

OrderedDict([('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20)])


In [ ]:
data = [('Ivan', 19),('Mark', 25),('Andrey', 23),('Maria', 20)]
ordered_client_ages = OrderedDict(sorted(data, key=lambda x: x[1]))
print(ordered_client_ages)

OrderedDict([('Ivan', 19), ('Maria', 20), ('Andrey', 23), ('Mark', 25)])


In [ ]:
ordered_client_ages['Nikita'] = 18
print(ordered_client_ages)

OrderedDict([('Ivan', 19), ('Maria', 20), ('Andrey', 23), ('Mark', 25), ('Nikita', 18)])


In [ ]:
del ordered_client_ages['Andrey']
print(ordered_client_ages)
ordered_client_ages['Andrey'] = 23
print(ordered_client_ages)

OrderedDict([('Ivan', 19), ('Maria', 20), ('Mark', 25), ('Nikita', 18)])
OrderedDict([('Ivan', 19), ('Maria', 20), ('Mark', 25), ('Nikita', 18), ('Andrey', 23)])


In [ ]:
import sys
print(sys.version)

3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]


## DEQUE

In [ ]:
from collections import deque
dq = deque()
print(dq)

deque([])


In [ ]:
clients = deque()
clients.append('Ivanov')
clients.append('Petrov')
clients.append('Smirnov')
clients.append('Tikhonova')
print(clients)

deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])


In [ ]:
print(clients[2])

Smirnov


In [ ]:
first_client = clients.popleft()
second_client = clients.popleft()

print("First client:", first_client)
print("Second client:", second_client)
print(clients)

First client: Ivanov
Second client: Petrov
deque(['Smirnov', 'Tikhonova'])


In [ ]:
clients.appendleft('Vip-client')

print(clients)

deque(['Vip-client', 'Smirnov', 'Tikhonova'])


In [ ]:
tired_client = clients.pop()
print(tired_client, "left the queue")
print(clients)

Tikhonova left the queue
deque(['Vip-client', 'Smirnov'])


In [ ]:
clients = deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])
print(clients)
del clients[2]
print(clients)

deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])
deque(['Ivanov', 'Petrov', 'Tikhonova'])


In [ ]:
shop = deque([1, 2, 3, 4, 5])
print(shop)
shop.extend([11, 12, 13, 14, 15, 16, 17])
print(shop)

deque([1, 2, 3, 4, 5])
deque([1, 2, 3, 4, 5, 11, 12, 13, 14, 15, 16, 17])


In [ ]:
shop = deque([1, 2, 3, 4, 5])
print(shop)
shop.extendleft([11, 12, 13, 14, 15, 16, 17])
print(shop)

deque([1, 2, 3, 4, 5])
deque([17, 16, 15, 14, 13, 12, 11, 1, 2, 3, 4, 5])


In [ ]:
limited = deque(maxlen=3)
print(limited)

limited_from_list = deque([1,3,4,5,6,7], maxlen=3)
print(limited_from_list)

deque([], maxlen=3)
deque([5, 6, 7], maxlen=3)


In [ ]:
limited.extend([1,2,3])
print(limited)

print(limited.append(8))

print(limited)

deque([1, 2, 3], maxlen=3)
None
deque([2, 3, 8], maxlen=3)


In [ ]:
temps = [20.6, 19.4, 19.0, 19.0, 22.1,
        22.5, 22.8, 24.1, 25.6, 27.0,
        27.0, 25.6, 26.8, 27.3, 22.5,
        25.4, 24.4, 23.7, 23.6, 22.6,
        20.4, 17.9, 17.3, 17.3, 18.1,
        20.1, 22.2, 19.8, 21.3, 21.3,
        21.9]

In [ ]:
days = deque(maxlen=7)

for temp in temps:
    days.append(temp)
    if len(days) == days.maxlen:
        print(round(sum(days) / len(days), 2), end=';')
print("")

20.77;21.27;22.16;23.3;24.44;24.94;25.56;26.2;25.97;25.94;25.57;25.1;24.81;24.21;23.23;22.57;21.41;20.4;19.6;19.1;19.04;18.96;19.44;20.01;20.67;


In [ ]:
dq = deque([1,2,3,4,5])
print(dq)

dq.reverse()
print(dq)

deque([1, 2, 3, 4, 5])
deque([5, 4, 3, 2, 1])


In [ ]:
dq = deque([1,2,3,4,5])
print(dq)

dq.rotate(2)
print(dq)


deque([1, 2, 3, 4, 5])
deque([4, 5, 1, 2, 3])


In [ ]:
dq = deque([1,2,3,4,5])
print(dq)

dq.rotate(-2)
print(dq)

deque([1, 2, 3, 4, 5])
deque([3, 4, 5, 1, 2])


In [ ]:
dq = [1,2,4,2,3,1,5,4,4,4,4,4,3]
print(dq.index(4))
print(dq.count(4))

2
6


In [ ]:
dq = deque([1,2,4,2,3,1,5,4,4,4,4,4,3])
print(dq.index(25))

ValueError: 25 is not in deque

In [ ]:
dq = deque([1,2,4,2,3,1,5,4,4,4,4,4,3])
print(dq.count(25))

0


In [ ]:
dq = deque([1,2,4,2,3,1,5,4,4,4,4,4,3])
print(dq)
dq.clear()
print(dq)

deque([1, 2, 4, 2, 3, 1, 5, 4, 4, 4, 4, 4, 3])
deque([])


In [ ]:
temps = [('2000', -4.4), ('2001', -2.5), ('2002', -4.4), ('2003', -9.5)]

def check(tempss):
    dict = OrderedDict(sorted(temps, key=lambda x: x[1], reverse=True))
    return dict

print(check(temps))

OrderedDict([('2001', -2.5), ('2000', -4.4), ('2002', -4.4), ('2003', -9.5)])


In [ ]:
from collections import deque

def brackets(line):
    stash = deque()
    for i in line:
        if i == '(':
            stash.append(i)
        if i == ')':
            try:
                stash.pop()
            except IndexError:
                return False
    if len(stash) == 0:
        return True
    if len(stash) > 0:
        return False



print(brackets("(()())"))
print(brackets(""))
print(brackets("(()()))"))

True
True
False


In [ ]:
ratings = [('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8),
           ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1),
           ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)]

from collections import OrderedDict

cafes = OrderedDict(sorted(ratings, key=lambda x: (-x[1], x[0])))

print(cafes)
#OrderedDict([('WokAndRice', 4.9), ('WokToWork', 4.9), ('General Foods', 4.8), ('New Age', 4.6), ('Belissimo', 4.5),
#('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1), ('Nice Cakes', 3.9), ('Old Gold', 3.3),
#('Old Wine Cellar', 3.3), ('Old York', 3.3)])

OrderedDict([('WokAndRice', 4.9), ('WokToWork', 4.9), ('General Foods', 4.8), ('New Age', 4.6), ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1), ('Nice Cakes', 3.9), ('Old Gold', 3.3), ('Old Wine Cellar', 3.3), ('Old York', 3.3)])


In [ ]:
tasks = [(36871, 'office', False),
(40690, 'office', False),
(35364, 'voltage', False),
(41667, 'voltage', True),
(33850, 'office', False)]

from collections import defaultdict, deque
def task_manager(tasks):
    tasks = defaultdict(deque)
    for n, server, vip in tasks:
        if vip is True:
            tasks[server].appendleft(n)
        else:
            tasks[server].append(n)
    return tasks

print(task_manager(tasks))

defaultdict(<class 'collections.deque'>, {})


# 5. Модуль NumPy. Типы данных

In [24]:
import numpy as np

In [ ]:
print(-(2**16)/2)
print((2**16)/2-1)

-32768.0
32767.0


### ЦЕЛОЧИСЛЕННЫЕ ТИПЫ ДАННЫХ В NUMPY

In [ ]:
a = np.int8(25)
print(a)
print(type(a))

25
<class 'numpy.int8'>


In [ ]:
print(np.iinfo(np.int16))
print(np.iinfo(a))

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------



In [ ]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [ ]:
b = np.uint8(124)
print(b)
print(type(b))
np.iinfo(np.uint8)

124
<class 'numpy.uint8'>


iinfo(min=0, max=255, dtype=uint8)

In [ ]:
a = np.int32(1000)
print(a)
print(type(a))
a = 2056
print(a)
print(type(a))

1000
<class 'numpy.int32'>
2056
<class 'int'>


In [ ]:
a = np.int32(1000)
print(a)
print(type(a))
a = np.int32(2056)
print(a)
print(type(a))

1000
<class 'numpy.int32'>
2056
<class 'numpy.int32'>


In [ ]:
a = np.int32(1000)
b = a + 25
print(b)
print(type(b))

1025
<class 'numpy.int32'>


In [ ]:
a = np.int32(1000)
b = np.int8(25)
c = a + b
print(c)
print(type(c))

1025
<class 'numpy.int32'>


In [ ]:
a = np.int8(260)
print(a)

4


C:\Users\22775\AppData\Local\Temp\ipykernel_28664\464275206.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 260 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  a = np.int8(260)


In [ ]:
a = np.int32(2147483610)
b = np.int32(2147483605)
print(a, b)
print(a + b)

2147483610 2147483605
-81


C:\Users\22775\AppData\Local\Temp\ipykernel_28664\1517369409.py:4: RuntimeWarning: overflow encountered in scalar add
  print(a + b)


In [ ]:
a = np.int32(2147483610)
b = np.int32(2147483605)
print(a, b)
print(np.int64(a) + np.int64(b))

2147483610 2147483605
4294967215


### ТИПЫ ДАННЫХ С ПЛАВАЮЩЕЙ ТОЧКОЙ В NUMPY

In [ ]:
print(np.finfo(np.float16))
print(np.finfo(np.float32))
print(np.finfo(np.float64))

Machine parameters for float16
---------------------------------------------------------------
precision =   3   resolution = 1.00040e-03
machep =    -10   eps =        9.76562e-04
negep =     -11   epsneg =     4.88281e-04
minexp =    -14   tiny =       6.10352e-05
maxexp =     16   max =        6.55040e+04
nexp =        5   min =        -max
smallest_normal = 6.10352e-05   smallest_subnormal = 5.96046e-08
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1.4012985e-45
---------------------------------------------------------------

Machine parameters for float64
---

In [ ]:
print(np.float16(4.12))
print(np.float16(4.13))
print(np.float16(4.123))
print(np.float16(4.124))
print(np.float16(4.125))

4.12
4.13
4.12
4.125
4.125


### ДОПОЛНИТЕЛЬНЫЕ ТИПЫ ДАННЫХ В NUMPY

In [ ]:
#print(np.sctypeDict)
print(len(np.sctypeDict))

132


In [ ]:
print(*sorted(map(str, set(np.sctypeDict.values()))), sep='\n')

<class 'numpy.bool_'>
<class 'numpy.bytes_'>
<class 'numpy.clongdouble'>
<class 'numpy.complex128'>
<class 'numpy.complex64'>
<class 'numpy.datetime64'>
<class 'numpy.float16'>
<class 'numpy.float32'>
<class 'numpy.float64'>
<class 'numpy.int16'>
<class 'numpy.int32'>
<class 'numpy.int64'>
<class 'numpy.int8'>
<class 'numpy.intc'>
<class 'numpy.longdouble'>
<class 'numpy.object_'>
<class 'numpy.str_'>
<class 'numpy.timedelta64'>
<class 'numpy.uint16'>
<class 'numpy.uint32'>
<class 'numpy.uint64'>
<class 'numpy.uint8'>
<class 'numpy.uintc'>
<class 'numpy.void'>


In [ ]:
print(np.uint8(-456))

56


C:\Users\22775\AppData\Local\Temp\ipykernel_28664\2324658389.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -456 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  print(np.uint8(-456))


# 6. Модуль NumPy. Массивы

### МАССИВЫ В NUMPY

#### СОЗДАНИЕ МАССИВА ИЗ СПИСКА

In [ ]:
arr = np.array([1,5,2,9,10])
display(arr)
print(type(arr))

array([ 1,  5,  2,  9, 10])

<class 'numpy.ndarray'>


In [ ]:
arr = np.array([
    [12, 45, 78],
    [34, 56, 13],
    [12, 98, 76]
])
display(arr)

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

#### ТИПЫ ДАННЫХ В МАССИВЕ

In [ ]:
arr = np.array([1,5,2,9,10])
arr.dtype

dtype('int32')

In [ ]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr

array([ 1,  5,  2,  9, 10], dtype=int8)

In [ ]:
arr[2] = 2000
arr

C:\Users\22775\AppData\Local\Temp\ipykernel_28664\4005198755.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 2000 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  arr[2] = 2000


array([  1,   5, -48,   9,  10], dtype=int8)

In [ ]:
arr[2] = 125.5
arr

array([  1,   5, 125,   9,  10], dtype=int8)

In [ ]:
arr[2] = '12'
arr

array([ 1,  5, 12,  9, 10], dtype=int8)

In [ ]:
arr[2] = 'test'
arr

ValueError: invalid literal for int() with base 10: 'test'

In [ ]:
arr = np.float64(arr)
arr

array([ 1.,  5., 12.,  9., 10.])

In [ ]:
arr = np.array([12321, -1234, 3435, -214, 100], dtype=np.int32)
display(arr)
arr = np.uint8(arr)
arr

array([12321, -1234,  3435,  -214,   100])

array([ 33,  46, 107,  42, 100], dtype=uint8)

In [ ]:
arr = np.array([345234, 876362.12, 0, -1000, 99999999], dtype=np.float32)
arr

array([ 3.452340e+05,  8.763621e+05,  0.000000e+00, -1.000000e+03,
        1.000000e+08], dtype=float32)

In [ ]:
arr = np.array([345234, 876362.12, 0, -1000, 99999999], dtype=np.float64)
arr

array([ 3.4523400e+05,  8.7636212e+05,  0.0000000e+00, -1.0000000e+03,
        9.9999999e+07])

#### СВОЙСТВА NUMPY-МАССИВОВ

In [ ]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

In [ ]:
# Узнать размерность массива можно с помощью .ndim:
print(arr.ndim)
print(nd_arr.ndim)

1
2


In [ ]:
# Узнать общее число элементов в массиве можно с помощью .size:
print(arr.size)
print(nd_arr.size)

5
9


In [ ]:
# Форма или структура массива хранится в атрибуте .shape:
print(arr.shape)
print(nd_arr.shape)

(5,)
(3, 3)


In [ ]:
#Наконец, узнать, сколько «весит» каждый элемент массива в байтах позволяет .itemsize:
print(arr.itemsize)
print(nd_arr.itemsize)

1
2


### ЗАПОЛНЕНИЕ НОВЫХ МАССИВОВ

In [ ]:
zeros_1d = np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

In [ ]:
zeros_3d = np.zeros((5, 4, 3), dtype=np.float32)
print(zeros_3d.shape)

(5, 4, 3)


In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(2.5, 5)

array([2.5, 3.5, 4.5])

In [ ]:
np.arange(2.5, 5, 0.5, dtype=np.float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

In [ ]:
arr = np.linspace(1, 2, 10)
arr

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [ ]:
arr = np.linspace(1, 2, 10, endpoint=False)
arr

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [ ]:
arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)
print(step)
arr

0.1111111111111111


array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [ ]:
arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True)
print(step)
arr

0.1


array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [ ]:
arr, step = np.linspace(-6, 21, 60, retstep=True)
arr
print(round(step, 2))

0.46


In [ ]:
arr, step = np.linspace(-6, 21, 60,endpoint=False, retstep=True)
arr
print(round(step, 2))

0.45


# 7. Модуль NumPy. Действия с массивами

## ДЕЙСТВИЯ С МАССИВАМИ

### ИЗМЕНЕНИЕ ФОРМЫ МАССИВА

In [25]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [27]:
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [29]:
arr = np.arange(8)
arr_new = arr.reshape((2 ,4))
arr_new

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [30]:
arr = np.arange(8)
arr_new = arr.reshape((2 ,4), order='F')
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [31]:
arr = np.arange(8)
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [32]:
arr_trans = arr.transpose()
arr_trans

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [33]:
arr = np.arange(3)
print(arr.shape)
arr_trans = arr.transpose()
print(arr_trans.shape)

(3,)
(3,)


### ИНДЕКСЫ И СРЕЗЫ В МАССИВАХ

In [34]:
arr = np.linspace(1, 2, 6)
arr

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [35]:
print(arr[2])

1.4


In [36]:
print(arr[2:4])

[1.4 1.6]


In [37]:
print(arr[::-1])

[2.  1.8 1.6 1.4 1.2 1. ]


In [38]:
nd_array = np.linspace(0, 6, 12, endpoint=False).reshape(3,4)
nd_array

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [39]:
nd_array[1][2]

3.0

In [40]:
nd_array[1, 2]

3.0

In [41]:
nd_array[:2, 2]

array([1., 3.])

In [44]:
nd_array[1:, 2:4]

array([[3. , 3.5],
       [5. , 5.5]])

In [45]:
nd_array[:, 2:4]

array([[1. , 1.5],
       [3. , 3.5],
       [5. , 5.5]])

In [46]:
nd_array[:2]

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5]])

In [109]:
mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)

print(mystery[4, 2])
print(mystery[-1, -1])
print(mystery[3])
print(mystery[:,-2])
print(mystery[1:4,2:5])
print()
print(mystery[::-1, -1])
print(mystery.transpose())

30305
-32037
[13240  7994 32592 20149 13754 11795  -564]
[-17182  15790  25397  11795  12578    -47]
[[-1297 -4593  6451]
 [28655 -6012 21762]
 [32592 20149 13754]]

[-32037  29943   -564   8225   7181 -18049]
[[-13586  25936  13348  13240 -21725 -16841]
 [ 15203 -30968  28049   7994  -8681 -25392]
 [ 28445  -1297  28655  32592  30305 -17278]
 [-27117  -4593  -6012  20149  22260  11740]
 [ -1781   6451  21762  13754 -17918   5916]
 [-17182  15790  25397  11795  12578    -47]
 [-18049   7181   8225   -564  29943 -32037]]


### СОРТИРОВКА ОДНОМЕРНЫХ МАССИВОВ

In [81]:
arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
print(arr)
print(arr_new)

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]


In [82]:
arr = np.array([23,12,45,12,23,4,15,3])
print(arr.sort())
print(arr)

None
[ 3  4 12 12 15 23 23 45]


### РАБОТА С ПРОПУЩЕННЫМИ ДАННЫМИ

In [83]:
data = np.array([4, 9, -4, 3])

In [84]:
roots = np.sqrt(data)
roots

C:\Users\22775\AppData\Local\Temp\ipykernel_27552\3752651322.py:1: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081])

In [85]:
print(type(None))
print(type(np.nan))
type(np.nan)

<class 'NoneType'>
<class 'float'>


float

In [86]:
print(None == None)
print(np.nan == np.nan)

True
False


In [87]:
print(None is None)
print(np.nan is np.nan)
print(np.nan is None)

True
True
False


In [88]:
sum(roots)

nan

In [89]:
np.isnan(roots)

array([False, False,  True, False])

In [90]:
roots[np.isnan(roots)]

array([nan])

In [91]:
roots[np.isnan(roots)] = 0
roots

array([2.        , 3.        , 0.        , 1.73205081])

In [92]:
sum(roots)

6.732050807568877

In [108]:
mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)


nans_index = np.isnan(mystery)
print(nans_index)
n_nan = nans_index.sum()
print(n_nan)
mystery_new = mystery
mystery_new[np.isnan(mystery_new)] = 0
print(mystery_new)
#mystery_int = np.int32(mystery)
#print(mystery_int)
array = np.sort(mystery)
print(array)
table = array.reshape((5 ,3), order='F')
print(table)
col = table[:,1]
print(col)

[False False False  True False False False False  True False False False
  True False False]
3
[ 12279. -26024.  28745.      0.  31244.  -2365.  -6974.  -9212.      0.
 -17722.  16132.  25933.      0. -16431.  29810.]
[-26024. -17722. -16431.  -9212.  -6974.  -2365.      0.      0.      0.
  12279.  16132.  25933.  28745.  29810.  31244.]
[[-26024.  -2365.  16132.]
 [-17722.      0.  25933.]
 [-16431.      0.  28745.]
 [ -9212.      0.  29810.]
 [ -6974.  12279.  31244.]]
[-2365.     0.     0.     0. 12279.]


# 8. Модуль NumPy. Операции с векторами

### ВЕКТОРЫ В NUMPY И АРИФМЕТИКА

In [1]:
import numpy as np
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 + vec2

array([14. , 10. , 10.6, 15.5])

In [2]:
list1 = [2, 4, 7, 2.5]
list2 = [12, 6, 3.6, 13]
list1 + list2

[2, 4, 7, 2.5, 12, 6, 3.6, 13]

In [3]:
[x + y for x, y in zip(list1, list2)]

[14, 10, 10.6, 15.5]

In [4]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 * vec2

array([24. , 24. , 25.2, 32.5])

In [5]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6])

vec1 * vec2

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [6]:
vec = np.arange(5)
print(vec * 10)
print(vec ** 2)

[ 0 10 20 30 40]
[ 0  1  4  9 16]


In [7]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 > vec2

array([False, False,  True, False])

In [8]:
vec = np.array([14,15,9,26,53,5,89])
vec <= 26

array([ True,  True,  True,  True, False,  True, False])

### ПРОДВИНУТЫЕ ОПЕРАЦИИ С ВЕКТОРАМИ

In [9]:
vec = np.array([3, 4])

In [11]:
length = np.sqrt(np.sum(vec ** 2))
print(length)

5.0


In [12]:
length = np.linalg.norm(vec)
print(length)

5.0


In [13]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.sqrt(np.sum((vec1 - vec2) ** 2))
distance

12.206555615733702

In [15]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.linalg.norm(vec1 - vec2)
distance

12.206555615733702

In [16]:
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
scalar_product = np.sum(vec1 * vec2)
scalar_product

250.0

In [17]:
scalar_product = np.dot(vec1 , vec2)
scalar_product

250.0

In [18]:
x = np.array([25, 0])
y = np.array([0, 10])
np.dot(x, y)

0

### БАЗОВЫЕ СТАТИСТИЧЕСКИЕ ФУНКЦИИ ДЛЯ ВЕКТОРОВ

In [20]:
vec = np.array([2,7,18,28,18,1,8,4])
print(vec.min())
print(np.max(vec))
print(vec.mean())

1
28
10.75


# 9. Модуль NumPy. Случайные числа

### СЛУЧАЙНЫЕ ЧИСЛА В NUMPY

In [1]:
import numpy as np

#### ГЕНЕРАЦИЯ FLOAT

In [5]:
np.random.rand()

0.9459727743414877

In [8]:
np.random.rand() * 100

68.4342878820509

In [17]:
print(np.random.rand(5))
print(np.random.rand(2, 3))

[0.67616205 0.83505514 0.75134552 0.83238986 0.94530928]
[[0.61995603 0.45352208 0.71373133]
 [0.75686815 0.49878488 0.17175802]]


In [18]:
np.random.rand(2, 3, 4, 10, 12, 23)

array([[[[[[2.00819508e-01, 5.64684412e-01, 8.94487277e-01, ...,
            7.02431419e-01, 6.82749596e-01, 9.39226842e-01],
           [8.62276843e-01, 3.74244048e-01, 7.31888265e-01, ...,
            8.35890890e-01, 2.63070724e-01, 2.51618231e-01],
           [5.94475766e-01, 1.97267831e-01, 7.59822301e-01, ...,
            8.43341937e-01, 7.79721727e-01, 8.48163029e-01],
           ...,
           [6.56081713e-01, 9.90354309e-01, 6.14753134e-01, ...,
            9.24953640e-01, 7.75684745e-01, 9.75311535e-01],
           [8.01953631e-01, 2.46690168e-01, 4.43023975e-01, ...,
            9.10652314e-01, 1.50299855e-02, 5.16427889e-01],
           [6.66524450e-02, 6.85535928e-01, 7.44857458e-01, ...,
            5.29136497e-01, 5.09124100e-01, 3.03189491e-01]],

          [[3.77986862e-01, 6.17596119e-01, 6.21127765e-01, ...,
            5.10066954e-01, 2.74262146e-02, 1.49232838e-01],
           [1.75456756e-01, 8.68671068e-01, 8.44272937e-01, ...,
            4.91131456e-01, 8.31684

In [19]:
shape = (3, 4)
np.random.rand(shape)

TypeError: 'tuple' object cannot be interpreted as an integer

In [20]:
shape = (3, 4)
np.random.rand(*shape)

array([[0.05095889, 0.87765257, 0.27340417, 0.01929571],
       [0.64768421, 0.70576439, 0.73369095, 0.00132478],
       [0.74995508, 0.76105483, 0.23742563, 0.67046775]])

In [21]:
shape = (3, 4)
np.random.sample(shape)

array([[0.41918326, 0.59521265, 0.18598555, 0.21334302],
       [0.28086743, 0.92124881, 0.58694398, 0.07916703],
       [0.93019307, 0.8648038 , 0.0464819 , 0.06804725]])

In [22]:
np.random.uniform()

0.47938236788347743

In [23]:
np.random.uniform(-30, 50)

45.28769595496753

In [25]:
np.random.uniform(0.5, 0.750, size=(5))

array([0.67182594, 0.52541936, 0.58723777, 0.59068454, 0.50975373])

In [26]:
np.random.uniform(-1000, 500, size=(2, 3))

array([[  -9.2058375 ,  172.62950806,  -64.26186187],
       [-540.95763325, -452.9891428 , -344.26166766]])

#### ГЕНЕРАЦИЯ INT

In [28]:
np.random.randint(4, size=(2, 3))

array([[1, 2, 0],
       [1, 3, 3]])

In [29]:
np.random.randint(6, 12, size=(3,3))

array([[10, 10,  9],
       [ 7,  8,  8],
       [ 6, 10,  8]])

#### ГЕНЕРАЦИЯ ВЫБОРОК

In [45]:
arr = np.arange(6)
print(arr)
print(np.random.shuffle(arr))
arr

[0 1 2 3 4 5]
None


array([5, 3, 2, 0, 4, 1])

In [55]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(playlist)
print(shuffled)

['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']
['Deep Purple' 'ACDC' 'The Beatles' 'Pink Floyd']


In [56]:
np.random.permutation(10)

array([5, 3, 7, 1, 4, 9, 8, 0, 2, 6])

In [69]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
choice = np.random.choice(workers, size=2, replace=False)
print(choice)

['Ivan' 'Maria']


In [62]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
choice = np.random.choice(workers, size=10, replace=False)
print(choice)

ValueError: Cannot take a larger sample than population when 'replace=False'

In [74]:
choice = np.random.choice([1, 2, 3, 4, 5, 6], size=10)
print(choice)

[2 2 6 1 4 3 4 4 6 5]


#### SEED ГЕНЕРАТОРА ПСЕВДОСЛУЧАЙНЫХ ЧИСЕЛ

In [80]:
np.random.seed(23)
np.random.randint(10, size=(3,4))

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])

In [84]:
np.random.seed(100)
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))

[8 8 3]
[7 7 0]
[4 2 5]


In [94]:
chess = np.zeros((2,2))
chess


array([[0., 0.],
       [0., 0.]])

In [141]:

def get_chess(a):
    chess = np.zeros((a, a))
    if a == 1:
        return chess
    else:
        chess[::2,1::2] = 1
        chess[1::2,::2] = 1
        return chess

get_chess(1)
# array([[0.]])

get_chess(4)
# array([[0., 1., 0., 1.],
#        [1., 0., 1., 0.],
#        [0., 1., 0., 1.],
#        [1., 0., 1., 0.]])

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [155]:
array = [1, 2, 3, 4, 5]

def shuffle_seed(array):
    seed = np.random.randint(0, (2**32), dtype=np.uint32)
    np.random.seed(seed)
    shuffled = np.random.permutation(array)
    return (shuffled, seed)



shuffle_seed(array)
# (array([1, 3, 2, 4, 5]), 2332342819)
shuffle_seed(array)
# (array([4, 5, 2, 3, 1]), 4155165971)

(array([3, 1, 2, 4, 5]), 3133032578)

In [162]:
def min_max_dist(*vectors):
    dists = list()
    print(len(vectors))
    print(*range(len(vectors)))
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            dists.append(np.linalg.norm(vectors[i] - vectors[j]))
    return (min(dists), max(dists))


vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])
 
min_max_dist(vec1, vec2, vec3)
# (5.196152422706632, 10.392304845413264)

3
0 1 2


(5.196152422706632, 10.392304845413264)

#### 10.9

Напишите функцию any_normal, которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает True, если есть хотя бы одна пара перпендикулярных векторов. Иначе возвращает False.

In [168]:
def any_normal(*vectors):
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            if np.dot(vectors[i] , vectors[j]) == 0:
                return True
    return False


vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])
print(any_normal(vec1, vec2, vec3))

True


In [174]:
def get_loto(num):
    arr = np.random.randint(1, 101, size=(num,5,5))
    return arr

get_loto(3)

array([[[ 59,  63,  77,  61,  61],
        [ 66,  27,  39,   7,  89],
        [ 91,  30,  19,  39,  61],
        [ 15,  25,  43,  46,  27],
        [ 19,  18,  45,  41,  86]],

       [[ 78,  59,  79,  85,  37],
        [ 23,  77,  36,   6,   5],
        [ 13,  72,  98,  13,   1],
        [ 19,  75,  92,  63,  98],
        [ 25,  41,  82, 100,  51]],

       [[ 63,   4,  81,  22,  68],
        [  1,  49,   8,  77,  78],
        [ 23,  21,  43,  65,  15],
        [ 36,  70,  16,  17,  66],
        [ 82,  64,  85,  69,  32]]])

In [185]:
def get_unique_loto(num):
    sample = np.arange(1, 101)
    res = list()
    for i in range(num):
        res.append(np.random.choice(sample, replace=False, size=(5, 5)))
    res = np.array(res)
    return res

get_unique_loto(3)

array([[[ 81,  60,  96,  53,  87],
        [ 24,  82,  21,  46,  20],
        [ 49,  73,  52,  80,  61],
        [  4,  33,   9,  29,  47],
        [ 11,  37,  48,  51, 100]],

       [[ 18,  17,  19,  52,  11],
        [ 86,   4,  91,  47,  88],
        [  5,  67,  68,  90,  25],
        [ 85,  54,  38,  87,  16],
        [ 39,  26,  53,  28,  42]],

       [[ 75,   6,  32,  23,  49],
        [ 15,  99,  47,  85,  57],
        [ 67,  53,  51,  38,  73],
        [ 31,  72,  91,  20,   7],
        [ 83,  44,  89,  79,  55]]])